# Generated by Django 4.0.5 on 2022-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Physcis', max_length=50, null=True),
        ),
    ]
